Added news database and started news rest
xi-effect/xieffect-backend pull request #136
Opened 2022-09-05 09:24 UTC by porebrikk

2022-09-07 10:13 UTC, niqzart requested changes
Поверхностный отзыв, лучше созваниваться и разбирать это целиком

2022-09-07 10:13 UTC, niqzart commented on xieffect/communities/services/news_db.py
> +class News(Base, Identifiable):
Классы называют единственным числом, поэтому я и сказал `Post`. Таблицы - множественным, причём указывать связиб здесь мы работаем с CS, поэтому будет `cs_posts`

2022-09-07 10:13 UTC, niqzart commented on xieffect/communities/services/news_db.py
> +        session.flush()
super().create и так вызывает flush(), не нужно вызывать его ещё раз

2022-09-07 10:13 UTC, niqzart commented on xieffect/communities/services/news_db.py
> +    def find_by_id(cls, session: sessionmaker, community_id: int, entry_id: int) -> News | None:
Сигнатура метода должна соответствовать сигнатуре в интерфейсе, PyCharm не просто так кричит на это. Искать только по id!

2022-09-07 10:13 UTC, niqzart commented on xieffect/communities/services/news_rst.py
> +    news_post_parser.add_argument("deleted", type=bool)
Возможность создать новость, которая сразу будет удалённой это шедевр, но точно не нужно

2022-09-07 10:13 UTC, niqzart commented on xieffect/communities/services/news_rst.py
> +    news_post_parser.add_argument("change_datetime", type=inputs.datetime)
Поля даты задаются сервером, пользователь это менять возможности иметь не должен

2022-09-07 10:13 UTC, niqzart commented on xieffect/communities/services/news_rst.py
> +        user_id = user.id
?

2022-09-07 10:13 UTC, niqzart commented on xieffect/communities/services/news_rst.py
> +        if (participant := session.get_first(select(Participant).filter_by(user_id=user_id))) is None:
Логика БД должна быть в _db файлах

2022-09-07 10:13 UTC, niqzart commented on xieffect/communities/services/news_rst.py
> +            update_news.change_datetime = datetime.utcnow().replace(microsecond=0)
Зачем mircosecond=0?

2022-09-07 10:13 UTC, niqzart commented on xieffect/communities/services/news_rst.py
> +            update_news.description = update_news.description if (description is None) else description
Лишние скобки, они в тернарных выражениях не нужны

2022-09-07 10:13 UTC, niqzart commented on xieffect/communities/services/news_rst.py
> +    news_change_parser.add_argument("title", type=str, required=True)
А если хочется изменить только описание?

2022-09-07 12:17 UTC, porebrikk commented on xieffect/communities/services/news_rst.py
> +            update_news.change_datetime = datetime.utcnow().replace(microsecond=0)
Без этого параметра дата изменения отображает те самые микросекунды, что неприятно выделяется на фоне даты создания новости

2022-09-07 16:37 UTC, niqzart commented on xieffect/communities/services/news_rst.py
> +            update_news.change_datetime = datetime.utcnow().replace(microsecond=0)
Но она должна иметь миллисекунды, это нужно для стабильности сортировки

2022-09-08 04:49 UTC, porebrikk commented on xieffect/communities/services/news_rst.py
> +            update_news.change_datetime = datetime.utcnow().replace(microsecond=0)
А вот об этом я не подумал.
Исправил)

2022-09-11 10:53 UTC, niqzart reviewed
Пробежался, отметил, что заметил

2022-09-11 10:53 UTC, niqzart commented on xieffect/communities/services/news_sio.py
> +    @controller.database_searcher(Community, use_session=True)
Наоборот, в первом use_session=True будет, а во втором False, сессия же не используется в самой функции, но используется в database_searcher-е

2022-09-11 10:53 UTC, niqzart commented on xieffect/communities/services/news_sio.py
> +    @controller.database_searcher(Community, use_session=True)
А, неактуально, потому что проверять роль здесь не нужно: в приглашениях за списком могли наблюдать только создатели, а вот за списком новостей могут наблюдать и простые участники (но надо проверить, что существует сообщество и что пользователь является участником)

2022-09-11 10:53 UTC, niqzart commented on xieffect/communities/services/news_sio.py
> +    @check_participant_role(ParticipantRole.OWNER, use_session=False)
Тоже самое по ролям

2022-09-11 10:53 UTC, niqzart commented on xieffect/communities/services/news_sio.py
> +    @controller.jwt_authorizer(User)
jwt_authorizer уже используется внутри check_participant_role, два раза применять его не нужно

2022-09-11 10:53 UTC, niqzart commented on xieffect/communities/services/news_sio.py
> +    @controller.jwt_authorizer(User, check_only=True)
тоже самое про jwt_authorizer

2022-09-11 10:53 UTC, niqzart commented on xieffect/communities/services/news_sio.py
> +            controller.abort(404, "News not found")
Post not found

2022-09-11 10:53 UTC, niqzart commented on xieffect/communities/services/news_sio.py
> +            controller.abort(404, "News not found")
Если выкидываем ошибку, то она должна быть задокументирована:
@controller.doc_abort(...)

2022-09-11 10:53 UTC, niqzart commented on xieffect/communities/services/news_sio.py
> +            controller.abort(404, "News not found")
Бонус: тут можно использовать @controller.database_searcher(Post)

2022-09-11 10:53 UTC, niqzart commented on xieffect/communities/services/news_sio.py
> +    @controller.jwt_authorizer(User, check_only=True)
Нет декоратора @controller.force_ack

2022-09-11 10:53 UTC, niqzart commented on xieffect/communities/services/news_sio.py
> +        return {"a": "Post was successfully deleted"}, 200
Достаточно просто ничего не возвращать, @controller.force_ack всё устроит

2022-09-11 10:53 UTC, niqzart commented on xieffect/communities/services/news_sio.py
> +    @controller.mark_duplex(Post.IndexModel, use_event=True)
Индекс модели для удаления будет многовато, просто community_id и post_id стоит вернуть

2022-09-11 10:53 UTC, niqzart commented on xieffect/communities/services/news_sio.py
> +        entry_id: int
post_id лучше + читается database_searcher-ом

2022-09-11 10:53 UTC, niqzart commented on xieffect/test/cs_news/news_sio_test.py
> +    result_data = ack.get("data", None)
Можно просто ack.get("data"), по умолчанию get возвращает None, если ничего не нашёл. Если у меня везде написано с None, значит у меня тоже неправильно написано))

2022-09-11 10:55 UTC, niqzart commented on xieffect/communities/services/news_sio.py
> +    @controller.mark_duplex(Post.IndexModel, use_event=True)
Хотя можешь пока оставить, сложные модели сложнее устроить

2022-09-11 11:02 UTC, niqzart commented on xieffect/communities/services/news_sio.py
> +    @controller.database_searcher(Community, use_session=True)
А, понял тут, что можно использовать `@check_participant_role(ParticipantRole.BASE, ...)`

2022-09-12 13:22 UTC, niqzart requested changes
Всё уже приняло форму, я ток чутка хочу навести красоту, ибо думаю, это последний ревью на эту задачку

2022-09-12 13:22 UTC, niqzart commented on xieffect/communities/services/news_db.py
> +    deleted = Column(Boolean, default=False)
Стоит добавить `nullable=False всем этим колонкам ради
```
explicit is better than implicit
```

2022-09-12 13:22 UTC, niqzart commented on xieffect/communities/services/news_db.py
> +        )
[format] Лучше:
```py
stmt = select(cls).filter_by(community_id=community_id, deleted=False)
return session.get_paginated(stmt, offset, limit)
```

2022-09-12 13:22 UTC, niqzart commented on xieffect/communities/services/news_db.py
> +    # Find list of community news by id
Либо убрать, либо в docstring

2022-09-12 13:22 UTC, niqzart commented on xieffect/communities/services/news_rst.py
> +        post = Post.find_by_id(session, entry_id)
Тут стоит использовать database_searcher, заменив entry_id на post_id

2022-09-12 13:22 UTC, niqzart commented on xieffect/communities/services/news_sio.py
> +            post.changed = datetime.utcnow().replace()
.replace() тут ничего не делает, можно убрать

2022-09-12 13:22 UTC, niqzart commented on xieffect/communities/services/news_sio.py
> +
Пустая строка ни к чему

2022-09-12 13:22 UTC, niqzart commented on xieffect/communities/services/news_sio.py
> +    @controller.mark_duplex(Post.IndexModel, use_event=True)
Можно использовать DeleteModel, похожее делается в приглашениях, там понятно, как BaseModel-и заставить работать через event.emit_convert

2022-09-12 13:22 UTC, niqzart commented on xieffect/test/cs_news/news_sio_test.py
> +from __lib__.flask_fullstack import dict_equal, check_code
from common

2022-09-12 13:22 UTC, niqzart commented on xieffect/test/cs_news/news_sio_test.py
> +from __lib__.flask_fullstack import dict_equal, check_code
Дальше тесты не проверяю, как будет нормальная система вернёмся к ним

2022-09-12 13:22 UTC, niqzart commented on xieffect/communities/services/news_db.py
> +    # Find list of community news by id
Тоже самое к остальным таким комментам

2022-09-12 13:24 UTC, niqzart commented on xieffect/communities/services/news_rst.py
> +        post = Post.find_by_id(session, entry_id)
А ещё стоит NewsChanger переименовать

2022-09-13 10:42 UTC, niqzart approved these changes

2022-09-13 21:06 UTC, merged