fix: some reordering & renaming (rst -> mub)
xi-effect/xieffect-backend pull request #151
Opened 2022-10-26 12:33 UTC by porebrikk

2022-10-26 15:24 UTC, niqzart commented on xieffect/users/invites_mub.py
> +class InviteMUBManager(Resource):
MUB в середине класса выглядит не очень, а старые названия были вполне норм

2022-10-26 15:24 UTC, niqzart commented on xieffect/users/invites_mub.py
> +beta_section = permission_index.add_section("beta-test")
beta_test_section тогда

2022-10-26 15:24 UTC, niqzart commented on xieffect/users/invites_mub.py
> +controller = MUBController("invites", path="/invites/")
Path по-умолчанию создаётся как `f"/{name}/"` (где `name` это первый аргумент конструктора)

2022-10-26 15:24 UTC, niqzart commented on xieffect/users/invites_mub.py
> +from users.invites_db import Invite
Кажется автоматика импорт сделала не локальным, надо бы вернуть его обратно как `from .invites_db import Invite`

2022-10-26 15:24 UTC, niqzart commented on xieffect/users/__init__.py
> +from .invites_mub import controller as invites_mub_namespace
А отсортировать импорты?))

2022-10-27 01:06 UTC, porebrikk commented on xieffect/users/invites_mub.py
> +controller = MUBController("invites", path="/invites/")
В emailer_mub подсмотрел)))

2022-10-27 08:47 UTC, niqzart commented on xieffect/users/invites_mub.py
> +controller = MUBController("invites", path="/invites/")
Ахахах, @niqzart ну какого чёрта

2022-10-27 08:47 UTC, niqzart approved these changes

2022-10-27 13:44 UTC, niqzart requested changes

2022-10-27 13:44 UTC, niqzart commented on xieffect/test/users/invites_mub_test.py
> +base_url = "/mub/invites"
А почему сразу не сделать `/mub/invites/`? Не нужно тогда будет писать `create_url = f"{base_url}/"`

2022-10-27 13:44 UTC, niqzart commented on xieffect/test/users/invites_mub_test.py
> +    assert dict_equal(invite, invite_data, "name", "limit", "accepted")
А тут можно вместо перечисления ключей вручную использовать `*invite_data.keys()`

2022-10-27 13:44 UTC, niqzart commented on xieffect/test/users/invites_mub_test.py
> +    assert (counter := len(invite_list)) != 0
Проверять, что список не пуст как-то странно, тесты не должны ломаться, если мы решим, например, не создавать приглашение тестовое

2022-10-27 13:44 UTC, niqzart commented on xieffect/test/users/invites_mub_test.py
> +    assert (counter := len(invite_list)) != 0
Бонус: invite_list какая-то не супер полезная переменная

2022-10-27 13:44 UTC, niqzart commented on xieffect/test/users/invites_mub_test.py
> +    lister_data = {"counter": 50, "offset": 0}
Использовано 1 раз и я уже объяснял, что counter и offset взаимоисключающие

2022-10-27 13:44 UTC, niqzart commented on xieffect/test/users/invites_mub_test.py
> +    lister_data = {"counter": 50, "offset": 0}
Здесь (и везде, где такая штука есть) должно быть просто {"offset": 0}

2022-10-28 16:18 UTC, niqzart approved these changes

2022-10-28 16:31 UTC, merged