MUB Feedback
xi-effect/xieffect-backend pull request #154
Opened 2022-10-30 02:36 UTC by porebrikk

2022-10-30 11:11 UTC, niqzart reviewed
А в остальном красивое

2022-10-30 11:11 UTC, niqzart commented on xieffect/test/users/feedback_test.py
> +    print(counter)
print))

2022-10-30 11:11 UTC, niqzart commented on xieffect/test/users/feedback_test.py
> +    get_url = f"/mub/feedback/{feedback['id']}/"
А что если код кривой и в feedback нет ключа id? Это тест тоже должен assert-ом проверить, а не иметь потенциал с KeyError упасть

2022-10-30 11:11 UTC, niqzart commented on xieffect/test/users/feedback_test.py
> +    get_url = f"/mub/feedback/{feedback['id']}/"
Тоже самое с получению по индексу: если сервер вернёт пустой список, тест должен провалится, а не упасть с IndexError

2022-10-30 11:11 UTC, niqzart commented on xieffect/test/users/feedback_test.py
> +    url, base_status, base_message = "/mub/feedback/dump/", 403, "Permission denied"
url не очень дискриптивно

2022-10-30 11:11 UTC, niqzart commented on xieffect/test/users/feedback_test.py
> +    url, base_status, base_message = "/mub/feedback/dump/", 403, "Permission denied"
403 в переменную выделять незачем

2022-10-30 11:11 UTC, niqzart commented on xieffect/test/users/feedback_test.py
> +    url, base_status, base_message = "/mub/feedback/dump/", 403, "Permission denied"
Permission denied в локальную переменную выделять странно

2022-11-04 14:34 UTC, niqzart requested changes

2022-11-04 14:34 UTC, niqzart commented on xieffect/users/feedback_db.py
> +)
Лучше классом

2022-11-04 14:34 UTC, niqzart commented on xieffect/vault/files_db.py
> +    # User-related
Тут комменты не нужны, тем более неправильные

2022-11-04 14:34 UTC, niqzart commented on xieffect/users/feedback_rst.py
> -        NO_AUTH_PROVIDED = "Neither the user is authorized, nor the code is provided"
А зачем убирать хороший функционал?

2022-11-04 14:34 UTC, niqzart commented on xieffect/users/feedback_rst.py
> +    )
type=int, action="append", тогда это будет массив int-ов

2022-11-04 14:34 UTC, niqzart commented on xieffect/users/feedback_rst.py
> +        files = list([File.find_by_id(file) for file in files])
Квадратные скобки это уже list

2022-11-04 14:34 UTC, niqzart commented on xieffect/users/feedback_rst.py
> +        files = list([File.find_by_id(file) for file in files])
Плюс лучше сделать метод для получения кучки файлов одним запросом к БД

2022-11-04 14:34 UTC, niqzart commented on xieffect/users/feedback_rst.py
> +        files = list([File.find_by_id(file) for file in files])
Плюс нет проверки на 404

2022-11-04 14:34 UTC, niqzart commented on xieffect/users/feedback_db.py
> +            self.files.append(file)
Там есть `self.files.extend`

2022-11-04 14:34 UTC, niqzart commented on xieffect/users/feedback_db.py
> +    def add_files(self, files: list) -> None:
Просто `list` это мало типизации

2022-11-04 14:34 UTC, niqzart commented on xieffect/users/feedback_db.py
> +    # User-related
Давай без комментов тут, они нужны на чём-то крупном, при понимании, что они значат

2022-11-04 14:34 UTC, niqzart commented on xieffect/users/feedback_db.py
> +    files = relationship("File", secondary=feedback_image, backref="feedbacks")
files нужно добавить в FullModel

2022-11-04 14:34 UTC, niqzart commented on xieffect/users/feedback_mub.py
> +        return Feedback.search_by_params(start, finish - start, data)
Всё ещё надо сделать нормально, а не через словари на два элемента и search_by_params. Везде по проекту для такого делают методы

2022-11-04 14:34 UTC, niqzart commented on xieffect/users/feedback_mub.py
> +        return Feedback.search_by_params(start, finish - start, data)
Есть граница DRY на читаемость. Должно быть DRY, но читабельно. Здесь плохо с читабельностью

2022-11-04 14:34 UTC, niqzart commented on xieffect/vault/__init__.py
> +from .files_db import File
Если добавляется такой импорт, надо бы это во всех файлах, которые используют 
```
from vault.files_db import File
```
Сделать
```
from vault import File
```
Бонус: в PyCharm есть крутая фича, Ctrl+Shift+F для поиска по всему проекту

2022-11-04 14:34 UTC, niqzart commented on xieffect/users/feedback_db.py
> +)
И тут почему-то нет `primary_key=True`

2022-11-04 14:37 UTC, niqzart commented on xieffect/test/users/feedback_test.py
> +    files: list[int] = [file[0].get("id") for file in files]
Это можно в один проход

2022-11-04 14:38 UTC, niqzart commented on xieffect/test/users/feedback_test.py
> +    get_url = f"/mub/feedback/{feedback['id']}/"
IndexError!

2022-11-04 14:39 UTC, niqzart commented on xieffect/test/users/feedback_test.py
> +
Нечитабельно

2022-11-04 14:41 UTC, niqzart commented on xieffect/test/users/feedback_test.py
> +
Бонус: сравнение правильнее писать так:
```
assert len(new_list) == counter
#      ^^^^^^^^^^^^^    ^^^^^^^
#      <реальное>    == <ожидаемое>
```

2022-11-05 00:40 UTC, porebrikk commented on xieffect/test/users/feedback_test.py
> +    get_url = f"/mub/feedback/{feedback['id']}/"
Список не может быть здесь пустым, потому что выше я сравниваю его с counter который так же не равен 0

2022-11-05 12:10 UTC, niqzart reviewed
Что ж, вот и мини-правки))

2022-11-05 12:10 UTC, niqzart commented on xieffect/users/feedback_db.py
> +    file_id = Column(Integer, ForeignKey("files.id"))
Можно primary_key=True в оба поля `_id` и убрать отдельный `id`

2022-11-05 12:10 UTC, niqzart commented on xieffect/users/feedback_db.py
> +        return db.session.get_paginated(stmt, offset, limit)
Лучше без тернарных операторов, просто 
```py
if user_id is not None:
    stmt = stmt.filter_by(user_id=user_id)
```

2022-11-05 12:10 UTC, niqzart commented on xieffect/users/feedback_rst.py
> +        required=True,
Надо бы `required=False`, тогда будет разрешено присылать пустой список (бывают же отзывы без файлов)

2022-11-05 12:10 UTC, niqzart commented on xieffect/users/feedback_rst.py
> +        files: list,
Мало типизации, это же список интов

2022-11-05 12:57 UTC, niqzart approved these changes

2022-11-05 14:31 UTC, niqzart approved these changes

2022-11-06 11:32 UTC, merged